/* console.log("Step1")
setTimeout(() => { console.log("Step2") }, 3000)
console.log("Step4") */

/* console.log("Welcome");
console.log("to");
console.log("Playwright");*/

/*console.log("Welcome");
console.log("Welcome");
console.log("Welcome");*/



let username = "Samraj";
let organization = "Axis";
let contactNumber = "9080368130";
let knowsAutomation = true;
let usesPlaywright;

console.log(username);
console.log(typeof username);
console.log(organization);
console.log(typeof organization);
console.log(contactNumber);
console.log(typeof contactNumber);
console.log(knowsAutomation);
console.log(typeof knowsAutomation);
console.log(usesPlaywright);
console.log(typeof usesPlaywright);
